apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-restarter.fullname" . }}
  labels:
    {{- include "k8s-restarter.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
