reconcilationInterval: 60s

restartInterval: 10m

# For example "k8s-restarter.kubernetes.io/enabled"
includeAnnotation: ""

# For example "k8s-restarter.kubernetes.io/ignore"
excludeAnnotation: ""

excludeNamespaces: []
