restartInterval: 10m

# For example "k8s-restarter.kubernetes.io/enabled"
includeAnnotation: "k8s-restarter.kubernetes.io/enabled"

excludeAnnotation: ""
excludeNamespaces:
  - kube-system
  - default
