# Default values for k8s-restarter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of replicas
replicaCount: 2

image:
  # -- Image Repository
  repository: shaardie/k8s-restarter
  # -- Image Pull Policy
  pullPolicy: IfNotPresent
  # -- Image Tag
  tag: "latest"

# -- ImagePullSecrets
imagePullSecrets: []

# -- Overrides `k8s-restarter.name`
nameOverride: ""

# -- Override `k8s-restarter.fullname`
fullnameOverride: ""

serviceAccount:
  # -- Enable Service Account
  create: true
  # -- Annotations for the Service Account
  annotations: {}
  # -- Name of the Service Account, `k8s-restarter.fullname`, if not set
  name: ""

# Annotations for the Pods
podAnnotations: {}

metrics:
  # -- Enable Metrics Scraping using Prometheus
  enabled: false

# -- Pod Security Policy
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

# -- Security Context
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

service:
  # -- Service Type
  type: ClusterIP
  # -- Service Port
  port: 80

# -- Resource Limits
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Node labels for pod assignment
nodeSelector: {}

# -- Tolerations for pod assignment
tolerations: []

# -- Affinity for pod assignment
affinity: {}

# Configuration for the K8s Restarter.
config:
  # -- Interval for reconcilation loop
  reconcilationInterval: 60s

  # -- Apps running this interval longs are restarted
  restartInterval: 10m

  include:
    # -- Enable whitelist include selectors.
    enabled: false
    # -- List of selectors. Can be selected on Namespace, Labels or both.
    selectors: []
      # - namespace: kube-system
      #   matchLabels:

  exclude:
    # -- Enable blacklist exclude selectors.
    enabled: false
    # -- List of selectors. Can be selected on Namespace, Labels or both.
    selectors: []
      # - namespace: kube-system
      #   matchLabels:
