name: Test
on: [push, pull_request]
jobs:
  go-test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: make test
      - name: Test Build
        run: make k8s-restarter
  helm-test:
    strategy:
      matrix:
        helm-version: [v3.9.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Helm
        run: curl https://get.helm.sh/helm-${{ matrix.helm-version }}-linux-amd64.tar.gz | sudo tar xzf - --strip-components 1 -C /usr/bin/ linux-amd64/helm
      - name: Helm Lint
        run: make helm-lint
      - name: Helm Template
        run: helm template k8s-restarter ./charts/k8s-restarter
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: make image
